---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-image-ws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cache-image-pipelinerun
  labels:
    app.kubernetes.io/description: PipelineRun
spec:
  pipelineRef:
    name: buildpacks
  params:
    - name: BUILDER_IMAGE
      value: docker.io/cnbs/sample-builder:bionic@sha256:e81ef84a8c4fbe9522bb4ad0c889384df5554efd292548b48cc0606531e567dc
    - name: TRUST_BUILDER
      value: "true"
    - name: APP_IMAGE
      value: localhost:5000/cmoulliard/tekton-test
    - name: SOURCE_URL
      value: https://github.com/buildpacks/samples
    - name: SOURCE_SUBPATH
      value: apps/ruby-bundler
    - name: CACHE_IMAGE
      value: localhost:5000/cmoulliard/tekton-test-cache
  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: cache-image-ws-pvc
    # NOTE: Pipeline hangs if optional cache workspace is missing so we provide an empty directory
    - name: cache-ws
      emptyDir: {}