kind: Service
apiVersion: v1
metadata:
  name: stonesoup-spring-boot
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: stonesoup-spring-boot